version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000"
      - "9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set main http://minio:9000 minio minio123;
      /usr/bin/mc mb main/main;
      /usr/bin/mc policy set public main/main;
      exit 0;
      "

  cache:
    restart: always
    container_name: cache
    image: redis:6-alpine
    networks:
      - directus
    ports:
      - 6379

  database:
    container_name: database
    ports:
      - 8055
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  directus:
    restart: always
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    networks:
      - directus
      - caddy
    depends_on:
      - cache
     
    environment:
      KEY: '{{  directus_key  }}'
      SECRET: '{{  directus_secret  }}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'


      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_TTL: "5s"

      STORAGE_LOCATIONS: "s3"
      STORAGE_S3_DRIVER: "s3" 
      STORAGE_S3_KEY: "minio"
      STORAGE_S3_SECRET: "minio123"
      STORAGE_S3_BUCKET: "main"
      STORAGE_S3_ENDPOINT: "http://minio:9000"

      ADMIN_EMAIL: '{{ directus_admin_mail }}'
      ADMIN_PASSWORD: '{{  directus_admin_pw  }}'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_FROM: '{{ smtp_user }}'
      EMAIL_SMTP_HOST: 'mail.your-server.de'
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USER: '{{ smtp_user }}'
      EMAIL_SMTP_PASSWORD: "{{ smtp_password }}"
      EMAIL_SMTP_SECURE: 'true'

      PUBLIC_URL: "https://{{  domain  }}"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    
    labels:
      caddy: "{{ domain }}"
      caddy.reverse_proxy: "{{"{{upstreams 8055}}"}}"

  

networks:
  caddy:
    external: true
  directus:

volumes:
  caddy_data: {}

