---
- hosts: all
  gather_facts: true
  become: false
  vars_files:
    - group_vars/main.yml
    - group_vars/vault.yml

  tasks:
    - block:
        - name: Initial server setup (security etc.)
          include_role:
            name: jstet.initial_server_setup
          vars:
            extra_packages:
              - htop
              - net-tools
              - vim
              - ufw
              - git
              - libpq-dev 
              - python3-dev
              - python3-pip 
            firewall: false

        - name: Installing Docker
          include_role:
            name: geerlingguy.docker
          vars:
            docker_users:
              - "{{  user  }}"
            docker_daemon_options:
              features:
                buildkit: true
      become: true

    - name: Create dir for docker compose
      file:
        path: "/home/{{  user  }}/app"
        state: directory
        owner: "{{  user  }}"
        mode: 0775

    - name: Template docker compose to server
      template:
        src: "templates/docker-compose.yml"
        dest: "/home/{{  user  }}/app/docker-compose.yml"

    - name: creating network
      shell: |
        docker network inspect caddy >/dev/null 2>&1 || \
        docker network create caddy
    
    - name: Create dir for docker compose
      file:
        path: "/home/{{  user  }}/caddy"
        state: directory
        owner: "{{  user  }}"
        mode: 0775

    - name: copy caddy docker compose to server
      copy: 
        src: files/docker-compose.yml
        dest: "/home/{{  user  }}/caddy/docker-compose.yml"


    - name: deploying caddy
      shell: |
        cd caddy && docker compose up -d

    - name: deploying app
      shell: |
        cd app && docker compose up -d
